#default: &default
#  adapter: mysql2
#  encoding: utf8
#  pool: 5
#  username: root
#  password:
#  host: localhost

development:
  adapter: postgresql
  host: localhost
  username: postgres
  password:
  database: hello_rails_development
  encoding: utf8

test:
  adapter: postgresql
  host: localhost
  username: postgres
  password:
  encoding: utf8
  database: hello_rails_test

#production:
#  adapter: mysql2
#  encoding: utf8
#  database: hello_rails_production
#  username: root
#  password:
#  pool: 5

# heroku用の設定
production:
  adapter: postgresql
  encoding: unicode
  pool: 5